<?php

use App\Http\Controllers\ProfileController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ProductController;
use Illuminate\Support\Facades\Route;

// Redirect the root URL to the login page (Vue login)
Route::get('/', function () {
    return view('auth.login'); // Redirecting to the login view generated by Vue
})->name('vue.login'); // Changed the name to avoid conflict

// Authentication routes
Auth::routes(); // This registers routes like /login, /register, etc.

// Resourceful routes for products (only accessible after login)
Route::middleware(['auth'])->group(function () {

// Show product index (accessible to all users, Admin or Customer)
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

    Route::middleware('auth')->group(function () {
        Route::get('/profile/edit', [ProfileController::class, 'edit'])->name('profile.edit');
        Route::put('/profile', [ProfileController::class, 'update'])->name('profile.update');
    });
    
    // Resourceful routes for products, but restrict create and edit to Admin only
    Route::middleware('role:Admin')->group(function () {
        Route::get('/products/create', [ProductController::class, 'create'])->name('products.create');
        Route::post('/products', [ProductController::class, 'store'])->name('products.store');
        Route::get('/products/{product}/edit', [ProductController::class, 'edit'])->name('products.edit');
        Route::put('/products/{product}', [ProductController::class, 'update'])->name('products.update');
        Route::delete('/products/{product}', [ProductController::class, 'destroy'])->name('products.destroy');
    });

    Route::middleware(['auth', 'role:Admin'])->prefix('admin')->group(function () {
        Route::get('/users', [UserController::class, 'index'])->name('users.index');
        Route::resource('users', UserController::class);
    });

    // Allow all authenticated users to view products and purchase
    Route::get('/products', [ProductController::class, 'index'])->name('products.index'); // View all products
    Route::get('/products/{id}', [ProductController::class, 'show'])->name('products.show'); // View a single product

    // Custom route to handle buying a product and subtracting from stock
    Route::post('/products/{product}/buy', [ProductController::class, 'buy'])->name('products.buy');
});
